Lidar_front_end:
   lidar_type: 4   # 1 for Livox-avia, 3 for Ouster-OS1-6
   N_SCANS: 1
   using_raw_point: 1
   point_step: 1
   
r3live_common:
   if_dump_log: 0                   # If recording ESIKF update log. [default = 0]
   record_offline_map: 1            # If recording offline map. [default = 1]
   pub_pt_minimum_views: 3          # Publish points which have been render up to "pub_pt_minimum_views" time. [default = 3]
   minimum_pts_size: 0.01           # The minimum distance for every two points in Global map (unit in meter). [default = 0.01] 
   image_downsample_ratio: 1        # The downsample ratio of the input image. [default = 1]
   estimate_i2c_extrinsic: 1        # If enable estimate the extrinsic between camera and IMU. [default = 1] 
   estimate_intrinsic: 1            # If enable estimate the online intrinsic calibration of the camera lens. [default = 1] 
   maximum_vio_tracked_pts: 600     # The maximum points for tracking. [default = 600]
   append_global_map_point_step: 4  # The point step of append point to global map. [default = 4]
   transform_imu: true              # just for custom use ----- songfangjing

r3live_vio:
   resize: true                     # just for cutom use ----- songfangjing
   # image_width: 2048
   # image_height: 1536
   # camera_intrinsic:
   #    [973.612, 0.0, 1026.69,
   #    0.0,  973.43, 779.419,
   #    0.0, 0.0, 1.0 ]
   image_width: 1280
   image_height: 720
   camera_intrinsic:
      [619.837, 0.0, 643.405,
      0.0,  619.837, 369.722,
      0.0, 0.0, 1.0 ] 
   # camera_dist_coeffs: [-0.365917, -2.25056, 4.43552e-05, -0.000186923, 1.8093]  #k1, k2, p1, p2, k3
   camera_dist_coeffs: [0.07743,-0.03530507,0.00033,-0.00115634,0]  #k1, k2, p1, p2, k3
   # Fine extrinsic value. form camera-LiDAR calibration.
   # camera_ext_R:
   #       [0, 0, 1,
   #          -1,  0, 0,
   #          0,  -1,  0]
   camera_ext_R:
         [-0.4893158, -0.0291675, 0.8716187,
            -0.8720675,  0.0258335, -0.4887033,
            -0.0082627,  -0.9992406,  -0.0380768]
   # camera_ext_t: [0.050166, 0.0474116, -0.0312415] 
   camera_ext_t: [0.158371,-0.111619,-0.0613574] 
   # Rough extrinsic value, form CAD model, is not correct enough, but can be online calibrated in our datasets.
   # camera_ext_R:
   #    [0, 0, 1,
   #     -1, 0, 0,
   #     0, -1, 0]
   # camera_ext_t: [0,0,0] 
   
r3live_lio:        
   lio_update_point_step: 4   # Point step used for LIO update.  
   max_iteration: 2           # Maximum times of LIO esikf.
   lidar_time_delay: 0        # The time-offset between LiDAR and IMU, provided by user. 
   filter_size_corner: 0.30   # no use, is not this name
   filter_size_surf: 0.30
   filter_size_surf_z: 0.30
   filter_size_map: 0.30
   dense_map_enable: true

